import React,{useId} from 'react'

function InputBox({
    label,
    amount,
    onAmountChange,
    OnCurrencyChange,
    currencyOption=[], //to avoid code crash,if no data
    selectCurrency="usd",
    amountDisable=false,
    currencyDisable=false,
    className = "",
}) {

    //optimising : binding input and label with unique id generated by hook useId()=random ids genetered
    const amountInputId=useId();
   

    return (
        <div className={`bg-white p-3 rounded-lg text-sm flex ${className}`}>

            <div className="w-1/2">
                <label htmlFor={amountInputId} className="text-black/40 mb-2 inline-block">
                    {label}
                </label>
                <input 
                    id={amountInputId}
                    className="outline-none w-full bg-transparent py-1.5"
                    type="number"
                    placeholder="Amount"
                    disabled={amountDisable}
                    value={amount}
                    onChange={(e)=>onAmountChange && onAmountChange(Number(e.target.value)) }
                    //koe amount nahi raha to prblm ho jaega q ki dafault value nahi to crash kr jaega or function me default value nahi dete

                    
                />
            </div>

            <div className="w-1/2 flex flex-wrap justify-end text-right">
                <p className="text-black/40 mb-2 w-full">Currency Type</p>
                <select
                    className="rounded-lg px-1 py-1 bg-gray-100 cursor-pointer outline-none"
                    value={selectCurrency}
                    onChange={(e)=>OnCurrencyChange && OnCurrencyChange(e.target.value)}
                    disabled={currencyDisable}
                    >
                        {currencyOption.map((currency)=>(
                            <option key={currency} value={currency}>
                            {currency}
                            </option>
                            //key use krna imp hai nahi to dom creation me bar bar react ko hit milega ki kitne bar usne same element ke lia dom create kr lia
                        ))}     
                
                </select>
            </div>
        </div>
    );
}

export default InputBox;
